### PR TITLE
fix multiplayer combine number to a nil value

### PR DESCRIPTION
**Pull request by dabene1408**
Without this code I wasn't able to join a dedicated Multiplayer session

### CODE REVIEW

**Comment by yumi-modding** [comment]
Hello
Thx for the PR, could you please try instead to remove the parameter getXMLString in the call since i see the method signature changed and that might be the root issue.

**Comment by dabene1408** [comment]
I tried it without the getXMLString but got this Error:
```
2021-12-07 15:25   Error (data/vehicles/grimme/rootster604/rootster604.xml): Failed to validate xml path 'vehicle.motorized#hp' for 'vehicle'. Path not registered.
```
I'm very new to Scripting in FS19/FS22 so sorry for bothering you  :) 
With which IDE are you developing your mod?

**Comment by yumi-modding** [comment]
Thx for the test, I'll have a look.
That's good.to propose PR, even if you're new to scripting that's a good way to learn.

**Comment by yumi-modding** [comment]
Hello,
I think the issue is specific to this implement that is seen as a combine but has no motorized spec.
I will check how to fix it.
Thanks

**Pull request closed without merging**
